### ISSUE TITLE
Is version 0.1.3 actually released?

### ISSUE THREAD

**Issue by peterfortuin** [husseinala/neon#1]
The README.md is referring to version 0.1.3, but I can't seem to find / download it. 0.1.2 is working fine, but uses old apis of the compose library, so I can't use that into my Application. 

Is version 0.1.3 actually released?

**Comment by husseinala** [comment]
Hi Peter, it wasn't, but it should be up now. Sorry for the confusion.

**Comment by peterfortuin** [comment]
I directly upgraded to 0.1.4 and it worked like a charm! Thanks a lot!
