### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.foundation.layout.LayoutSizeKt"

### ISSUE THREAD

**Issue by ScottPierce** [husseinala/neon#2]
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.foundation.layout.LayoutSizeKt"

I'm getting this error on `1.0.0-alpha11` version of compose.

**Comment by husseinala** [comment]
Hi @ScottPierce, this issue should be fixed now in version [0.1.5](https://github.com/husseinala/neon/releases/tag/0.1.5).

**Comment by ScottPierce** [comment]
Cool, thanks!

**Comment by ScottPierce** [comment]
Confirmed fixed.
