### ISSUE TITLE
`ProvidePicassoLoader` should default to `Picasso.get()`

### ISSUE THREAD

**Issue by ScottPierce** [husseinala/neon#4]
I think it would be better to have `ProvidePicassoLoader` default to `Picasso.get()`, not `Picasso.Builder(context()).build()`. No sense in creating extra `Picasso` instances, and thus memory caches, by default. Right?

**Comment by husseinala** [comment]
@ScottPierce thank you for the suggestion, that definitely makes more sense. I've made the change and it should be included in the next release.
